# Generated by Django 6.0.4 on 2026-04-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='email',
        ),
    ]
